/**
 * Invariants for the all-in fee exhibit - blueprint 1.4, generated by 7.3.
 *
 * One sentence in the blueprint is the reason this file exists:
 *
 * > "success fees on cards computed from CapitalForge's `approvedCreditLimit` field, never
 * > `creditLimit`" (Seek Capital lesson).
 *
 * A success fee charged on what a client asked for rather than what an issuer granted is the
 * failure that ended another company. Pure functions, so every case is cheap to state.
 */

import { describe, expect, it } from 'vitest';
import { buildFeeExhibit } from '@bwc/contracts';
import { successFeeBasis } from '@bwc/placement';

const growth = { offerTier: 'growth' as const };

describe('the success fee comes from what was approved', () => {
  it('computes on the approved limit', () => {
    const result = buildFeeExhibit({
      ...growth,
      successFee: { ratePercent: 10, approvedCreditLimit: 85_000 },
    });

    expect(result.status).toBe('ok');
    if (result.status !== 'ok') return;

    const fee = result.value.lines.find((line) => line.label === 'Success fee');
    expect(fee?.amount).toBe(8_500);
    // The exhibit says which figure it used, in the document the client signs.
    expect(fee?.basis).toMatch(/Not the amount applied for/);
  });

  it('has nowhere to put a requested limit', () => {
    // The structural guard, asserted as a property of the type rather than of a code path.
    // `FeeExhibitInput` carries no field for an applied-for amount, and `successFeeBasis` takes a
    // single numeric argument - so there is no second figure for the arithmetic to reach for.
    const input = {
      ...growth,
      successFee: { ratePercent: 10, approvedCreditLimit: 85_000 },
    };

    expect(Object.keys(input.successFee).sort()).toEqual(['approvedCreditLimit', 'ratePercent']);
    expect(successFeeBasis.length).toBe(1);
  });

  it('reports the fee as contingent when no approval exists, rather than estimating', () => {
    // An estimate in a fee exhibit reads as a price. Estimating from the requested amount is
    // exactly the failure this module is built against.
    const result = buildFeeExhibit({ ...growth, successFee: { ratePercent: 10 } });

    expect(result.status).toBe('ok');
    if (result.status !== 'ok') return;

    const fee = result.value.lines.find((line) => line.label === 'Success fee');
    expect(fee?.amount).toBeNull();
    expect(result.value.knownTotal).toBe(0);
    expect(result.value.contingentLines[0]).toMatch(/No amount is stated because no approval/);
  });

  it('refuses a rate that is not a percentage', () => {
    for (const ratePercent of [-1, 101, Number.NaN]) {
      const result = buildFeeExhibit({ ...growth, successFee: { ratePercent } });
      expect(result.status, String(ratePercent)).toBe('refused');
    }
  });

  it('rejects a negative approved limit at the shared guard', () => {
    expect(() => successFeeBasis(-1)).toThrow(/non-negative/);
  });
});

describe('the total states what is known and names what is not', () => {
  it('excludes contingent lines from the total and lists them', () => {
    // A total that quietly includes a fee nobody has incurred is a misstatement; one that omits a
    // contingent fee without saying so is another.
    const result = buildFeeExhibit({
      ...growth,
      retainer: { amount: 5_000, whenCharged: 'On signature.' },
      monthly: { amount: 1_500, months: 6 },
      successFee: { ratePercent: 10 },
    });

    expect(result.status).toBe('ok');
    if (result.status !== 'ok') return;

    expect(result.value.knownTotal).toBe(5_000 + 9_000);
    expect(result.value.contingentLines).toHaveLength(1);
    expect(result.value.summary).toMatch(/Fees determinable today: \$14,000\.00/);
    expect(result.value.summary).toMatch(/1 contingent item/);
  });

  it('states a plain total when nothing is contingent', () => {
    const result = buildFeeExhibit({
      ...growth,
      retainer: { amount: 2_500, whenCharged: 'On signature.' },
    });

    if (result.status !== 'ok') throw new Error('expected an exhibit');
    expect(result.value.summary).toBe('Total fees for this engagement: $2,500.00.');
  });

  it('expands a monthly fee into its total so the client sees the whole commitment', () => {
    const result = buildFeeExhibit({ ...growth, monthly: { amount: 1_000, months: 12 } });
    if (result.status !== 'ok') throw new Error('expected an exhibit');

    const line = result.value.lines[0];
    expect(line?.amount).toBe(12_000);
    expect(line?.basis).toMatch(/\$1,000\.00 per month for 12 months/);
  });

  it('refuses an exhibit with no lines', () => {
    // An engagement with no fees should say so in the service agreement rather than shipping an
    // empty exhibit, which states nothing while looking like a statement.
    const result = buildFeeExhibit({ ...growth });
    expect(result.status).toBe('refused');
    if (result.status === 'refused') expect(result.reason).toMatch(/states nothing/);
  });

  it('carries a caller-supplied contingent line into the contingent list', () => {
    const result = buildFeeExhibit({
      ...growth,
      retainer: { amount: 1_000, whenCharged: 'On signature.' },
      otherLines: [
        {
          label: 'Third-party filing fees',
          amount: null,
          basis: 'Charged at cost where a provider requires a filing.',
          whenCharged: 'As incurred.',
        },
      ],
    });

    if (result.status !== 'ok') throw new Error('expected an exhibit');
    expect(result.value.knownTotal).toBe(1_000);
    expect(result.value.contingentLines).toContain('Third-party filing fees');
  });
});
